In [144]:
import csv
import pandas as pd
import numpy as np

In [155]:
def readCsv(name):
    data = pd.read_csv('/home/gracie/Documents/DaNaTravel/training/data/{}.csv'.format(name))
    print(len(data))
    data.head(10)
    return data

In [156]:
def removeEmptyRating(data):
    newData = data.dropna(how='any',subset=['Rating'])
    print(len(newData))
    newData.head(10)
    return newData

In [157]:
def removeUnvalidRating(data):
    dataChange = data
    dataChange['Rating'] = np.where(data['Rating'] < 3, 0, data['Rating'])
    newData = dataChange[dataChange.Rating != float(0)]
    print(len(newData))
    newData.head(10)
    return newData

In [158]:
def handleUserRatingTotal(data):
    newData = data[data['User Ratings Total'] >= 20]
    return newData

In [159]:
def resetIndex(data):
    newData = data
    newData.reset_index(inplace=True, drop=True)
    return newData

In [160]:
def handle_types(data):
    valid_types = ['lodging', 'point_of_interest', 'establishment', 'tourist_attraction', 'food', 'cafe', 'restaurant']
    invalid_types = ['point_of_interest', 'establishment']
    listRowRemove = []

    for i in range(len(data)):
        row = data.iloc[i]
        types = row['Types'].strip("']['").split("', '")
        if all(item in invalid_types for item in types) and len(types) == 2:
            listRowRemove.append(i)
        elif all(item in valid_types for item in types) == False:
            listRowRemove.append(i)

    newData = data.drop(listRowRemove)
    return newData

In [ ]:
# newData6.reset_index(inplace=True, drop=True)
# print(len(newData6))
# newData6

In [169]:
def write_csv(data):
    data.to_csv('/home/gracie/Documents/DaNaTravel/training/data/newData.csv', mode='a', index=False)

In [164]:
def write_header():
    header = ['ID', 'Name', 'Address', 'Latitude', 'Longitude', 'Opening Hours', 'Types', 'Rating', 'User Ratings Total']
    with open('/home/gracie/Documents/DaNaTravel/training/data/newData.csv', 'a', encoding='UTF8', newline='') as f:
        writer = csv.writer(f)
        writer.writerow(header)

In [170]:
fileNames = ['dong', 'nam', 'bac']
write_header()
for name in fileNames:
    print(name)
    data = readCsv(name)
    data = removeEmptyRating(data)
    data = removeUnvalidRating(data)
    data = handleUserRatingTotal(data)
    data = resetIndex(data)
    newData = handle_types(data)
    write_csv(newData)

dong
264
233
226
nam
480
382
367
bac
1167
828
799

In [184]:
def handleDuplicates(data):
    data = data.sort_values(by=['ID'])
    data = data.drop_duplicates(subset=['ID'], keep='last')
    return data

In [189]:
data = pd.read_csv('/home/gracie/Documents/DaNaTravel/training/data/newData.csv')
newData = handleDuplicates(data)
newData = resetIndex(newData)
newData

,ID,Name,Address,Latitude,Longitude,Opening Hours,Types,Rating,User Ratings Total
0,ChIJ-3wY7lEYQjERrJ9wTeoa-WQ,Blue Summer Hotel,"35 Tôn Thất Đạm, Xuân Hà, Thanh Khê, Đà Nẵng 5...",16.0720623,108.2013925,"['Monday: Open 24 hours', 'Tuesday: Open 24 ho...","['lodging', 'point_of_interest', 'establishment']",3.9,42
1,ChIJ-UBpozMYQjERDV3V1nrXEiM,Vinapha 2 Hotel,"19 Phạm Hồng Thái, Hải Châu 1, Hải Châu, Đà Nẵ...",16.0673508,108.2217765,['Monday: 12:00\u202fAM\u2009–\u200911:59\u202...,"['lodging', 'point_of_interest', 'establishment']",3,93
2,ChIJ13MshlIYQjERM4sqFu8lvyA,Ribo Coffee,"05 Thái Thị Bôi, Chính Gián, Thanh Khê, Đà Nẵn...",16.0682715,108.2011952,['Monday: 6:30\u202fAM\u2009–\u200910:30\u202f...,"['cafe', 'food', 'point_of_interest', 'establi...",4.1,306
3,ChIJ14kOf8kZQjERrdrrQPpiZKA,Mì Quảng Thi,"251 Hoàng Diệu, Nam Dương, Hải Châu, Đà Nẵng 5...",16.0585457,108.2172243,['Monday: 6:00\u202fAM\u2009–\u20091:29\u202fP...,"['restaurant', 'point_of_interest', 'food', 'e...",4.3,308
4,ChIJ2aT3UqMXQjER_rVaqCoyyWU,Chùa Linh Ứng,"Vườn Lâm Tỳ Ni, Hoàng Sa, Thọ Quang, Sơn Trà, ...",16.1002615,108.2777474,"['Monday: Open 24 hours', 'Tuesday: Open 24 ho...","['place_of_worship', 'point_of_interest', 'est...",4.7,1785
...,...,...,...,...,...,...,...,...,...
159,ChIJz8woKLsiQjERJLzsLSEla5s,Công ty CP Biển Tiên Sa,"7 Yết Kiêu, Thọ Quang, Sơn Trà, Đà Nẵng, Vietnam",16.121177,108.2232456,NaN,"['lodging', 'point_of_interest', 'establishment']",4.1,22
160,ChIJzX1dFjAZQjERswowf61V1fk,APEC Park,"365F+67X, Bình Hiên, Hải Châu, Đà Nẵng 550000,...",16.0581055,108.2232435,NaN,"['park', 'point_of_interest', 'establishment']",4.5,665
161,ChIJzXv66zIYQjERVMBsPtBAerU,Pariat Hotel & Apartment,"202, 204 Bạch Đằng, Phước Ninh, Hải Châu, Đà N...",16.0654286,108.2240243,"['Monday: Open 24 hours', 'Tuesday: Open 24 ho...","['lodging', 'point_of_interest', 'establishment']",3.9,565
162,ChIJzdmTxe8ZQjERbvAggIAHQLc,Minh Toan Galaxy Hotel,"306 Đ. 2 Tháng 9, Hoà Cường Bắc, Hải Châu, Đà ...",16.0442346,108.2227286,['Monday: 12:00\u202fAM\u2009–\u200912:00\u202...,"['lodging', 'restaurant', 'point_of_interest',...",4.2,1820
163,ID,Name,Address,Latitude,Longitude,Opening Hours,Types,Rating,User Ratings Total

In [190]:
newData.to_csv('/home/gracie/Documents/DaNaTravel/training/data/FinalData.csv', index=False)